apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default

  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.11.5
    helm:
      values: |
        service:
          type: ClusterIP
          port: 5000

        telemetry:
          enabled: false

        extraArgs:
          workers: "1"

        backendStore:
          postgres:
            enabled: true
            host: postgres-postgresql.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow123

        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow-artifacts
            path: ""
            awsAccessKeyId: minioadmin
            awsSecretAccessKey: minioadmin123

        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://minio.mlflow.svc.cluster.local:9000
          GUNICORN_CMD_ARGS: "--max-requests 100 --max-requests-jitter 20"

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true