apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-apps
  namespace: infra-tools
spec:
  generators:
    - git:
        repoURL: https://github.com/ValeriiYermak/MLOps-CI-CD.git
        revision: lesson_3
        directories:
          - path: hw_7/goit-argo/namespace/*

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ValeriiYermak/MLOps-CI-CD.git
        targetRevision: lesson_3
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true