apiVersion: batch/v1
kind: Job
metadata:
  generateName: promote-to-production-
  namespace: mlops-system
  labels:
    app: mlflow-registry-ops
    action: promote
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: mlflow-registry-ops
        action: promote
    spec:
      restartPolicy: Never
      containers:
        - name: promote
          image: localhost:5001/mlflow-registry-ops:v1
          args: ["registry/promote_to_production.py"]
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.mlops-system.svc.cluster.local:5000
