apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.6.4
    helm:
      values: |
        service:
          type: ClusterIP
        persistence:
          enabled: false
        adminUser: admin
        adminPassword: admin123
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki.monitoring.svc.cluster.local:3100
                access: proxy
                isDefault: false
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
            searchNamespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true